# Generated by Django 5.0.1 on 2025-10-29 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('pptx', 'PowerPoint'), ('pdf', 'PDF'), ('docx', 'Word')], default='pptx', max_length=10, verbose_name='エクスポート形式')),
                ('file_path', models.FileField(blank=True, upload_to='exports/%Y/%m/%d/', verbose_name='ファイルパス')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='ファイルサイズ（バイト）')),
                ('status', models.CharField(choices=[('pending', '処理待ち'), ('processing', '処理中'), ('completed', '完了'), ('failed', '失敗')], default='pending', max_length=20, verbose_name='ステータス')),
                ('error_message', models.TextField(blank=True, verbose_name='エラーメッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL, verbose_name='実行者')),
                ('talk_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='sales.talkscript', verbose_name='トークスクリプト')),
            ],
            options={
                'verbose_name': 'エクスポート履歴',
                'verbose_name_plural': 'エクスポート履歴',
                'ordering': ['-created_at'],
            },
        ),
    ]
