# Generated by Django 5.0.1 on 2025-10-29 03:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='テンプレート名')),
                ('template_type', models.CharField(choices=[('company_analysis', '企業情報分析'), ('product_extraction', '商品情報抽出'), ('product_matching', '商品マッチング'), ('script_opening', 'スクリプト：オープニング'), ('script_problem', 'スクリプト：課題特定'), ('script_solution', 'スクリプト：ソリューション提案'), ('script_objection', 'スクリプト：反論処理'), ('script_closing', 'スクリプト：クロージング'), ('custom', 'カスタム')], max_length=50, verbose_name='テンプレートタイプ')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('system_prompt', models.TextField(verbose_name='システムプロンプト')),
                ('user_prompt_template', models.TextField(verbose_name='ユーザープロンプトテンプレート')),
                ('model_override', models.CharField(blank=True, choices=[('', 'システムデフォルト'), ('gpt-4o', 'GPT-4o'), ('gpt-4o-mini', 'GPT-4o Mini')], max_length=50, verbose_name='モデル上書き')),
                ('temperature_override', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Temperature上書き')),
                ('version', models.IntegerField(default=1, verbose_name='バージョン')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('is_default', models.BooleanField(default=False, verbose_name='デフォルト')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prompts', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_prompts', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'プロンプトテンプレート',
                'verbose_name_plural': 'プロンプトテンプレート',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.IntegerField(default=1, unique=True)),
                ('max_csv_file_size_mb', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='CSV最大ファイルサイズ（MB）')),
                ('allowed_csv_encodings', models.JSONField(blank=True, default=list, verbose_name='許可するCSVエンコーディング')),
                ('default_ai_model', models.CharField(choices=[('gpt-4o', 'GPT-4o（高品質）'), ('gpt-4o-mini', 'GPT-4o Mini（コスト重視）')], default='gpt-4o', max_length=50, verbose_name='デフォルトAIモデル')),
                ('ai_temperature', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='AIのTemperature')),
                ('max_tokens_per_request', models.IntegerField(default=4000, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(16000)], verbose_name='1リクエストあたりの最大トークン数')),
                ('daily_token_limit', models.IntegerField(default=1000000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='1日のトークン上限')),
                ('scraping_enabled', models.BooleanField(default=True, verbose_name='スクレイピング機能を有効化')),
                ('scraping_timeout_seconds', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)], verbose_name='スクレイピングタイムアウト（秒）')),
                ('scraping_delay_seconds', models.FloatField(default=2.0, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(10.0)], verbose_name='スクレイピング間隔（秒）')),
                ('respect_robots_txt', models.BooleanField(default=True, verbose_name='robots.txtを尊重')),
                ('max_pdf_file_size_mb', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='PDF最大ファイルサイズ（MB）')),
                ('pdf_processing_enabled', models.BooleanField(default=True, verbose_name='PDF処理を有効化')),
                ('session_timeout_minutes', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)], verbose_name='セッションタイムアウト（分）')),
                ('max_login_attempts', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10)], verbose_name='最大ログイン試行回数')),
                ('lockout_duration_minutes', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)], verbose_name='アカウントロック時間（分）')),
                ('enable_email_notifications', models.BooleanField(default=False, verbose_name='メール通知を有効化')),
                ('admin_email', models.EmailField(blank=True, max_length=254, verbose_name='管理者メールアドレス')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='メンテナンスモード')),
                ('maintenance_message', models.TextField(blank=True, verbose_name='メンテナンスメッセージ')),
                ('system_announcement', models.TextField(blank=True, verbose_name='システムお知らせ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'システム設定',
                'verbose_name_plural': 'システム設定',
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='バージョン')),
                ('system_prompt', models.TextField(verbose_name='システムプロンプト')),
                ('user_prompt_template', models.TextField(verbose_name='ユーザープロンプトテンプレート')),
                ('change_summary', models.TextField(blank=True, verbose_name='変更内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('prompt_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.prompttemplate', verbose_name='プロンプトテンプレート')),
            ],
            options={
                'verbose_name': 'プロンプトバージョン',
                'verbose_name_plural': 'プロンプトバージョン',
                'ordering': ['-version'],
                'unique_together': {('prompt_template', 'version')},
            },
        ),
    ]
