# Generated by Django 5.0.1 on 2025-10-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='ai_enabled',
            field=models.BooleanField(default=True, help_text='AI機能（分析、スクリプト生成など）を有効にする', verbose_name='AI機能を有効化'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='OpenAI APIキーを入力してください。空の場合は環境変数から取得します。', max_length=255, verbose_name='OpenAI APIキー'),
        ),
    ]
