# Generated by Django 5.0.1 on 2025-10-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemsettings_ai_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttemplate',
            name='template_type',
            field=models.CharField(choices=[('csv_analysis', 'CSV解析'), ('company_analysis', '企業情報分析'), ('product_extraction', '商品情報抽出'), ('product_matching', '商品マッチング'), ('script_opening', 'トークスクリプト：オープニング'), ('script_problem', 'トークスクリプト：課題特定'), ('script_solution', 'トークスクリプト：ソリューション提案'), ('script_objection', 'トークスクリプト：反論処理'), ('script_closing', 'トークスクリプト：クロージング'), ('script_generate', 'トークスクリプト：生成（全体）'), ('custom', 'カスタム')], max_length=50, verbose_name='テンプレートタイプ'),
        ),
    ]
