# Generated by Django 5.0.1 on 2025-10-29 03:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='企業URL')),
                ('domain', models.CharField(max_length=255, verbose_name='ドメイン')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='ページタイトル')),
                ('meta_description', models.TextField(blank=True, verbose_name='メタディスクリプション')),
                ('main_content', models.TextField(blank=True, verbose_name='メインコンテンツ')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='企業名')),
                ('business_description', models.TextField(blank=True, verbose_name='事業内容')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='業界')),
                ('key_services', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None, verbose_name='主要サービス')),
                ('target_market', models.TextField(blank=True, verbose_name='ターゲット市場')),
                ('ai_summary', models.TextField(blank=True, verbose_name='AI生成サマリー')),
                ('pain_points', models.JSONField(blank=True, default=list, verbose_name='推定される課題')),
                ('scrape_status', models.CharField(choices=[('success', '成功'), ('partial', '部分的'), ('failed', '失敗')], default='success', max_length=20, verbose_name='スクレイピング状態')),
                ('scraped_at', models.DateTimeField(auto_now=True, verbose_name='取得日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '企業情報',
                'verbose_name_plural': '企業情報',
                'ordering': ['-scraped_at'],
            },
        ),
    ]
