# Generated by Django 5.0.1 on 2025-10-29 03:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/csv/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'txt'])], verbose_name='CSVファイル')),
                ('file_name', models.CharField(max_length=255, verbose_name='ファイル名')),
                ('file_size', models.IntegerField(verbose_name='ファイルサイズ（バイト）')),
                ('row_count', models.IntegerField(blank=True, null=True, verbose_name='行数')),
                ('column_count', models.IntegerField(blank=True, null=True, verbose_name='列数')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_uploads', to=settings.AUTH_USER_MODEL, verbose_name='アップロード者')),
            ],
            options={
                'verbose_name': 'CSVアップロード',
                'verbose_name_plural': 'CSVアップロード',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='分析プロンプト')),
                ('result', models.TextField(blank=True, verbose_name='分析結果')),
                ('model_used', models.CharField(blank=True, max_length=50, verbose_name='使用モデル')),
                ('token_count', models.IntegerField(blank=True, null=True, verbose_name='使用トークン数')),
                ('status', models.CharField(choices=[('pending', '処理待ち'), ('processing', '処理中'), ('completed', '完了'), ('failed', '失敗')], default='pending', max_length=20, verbose_name='ステータス')),
                ('error_message', models.TextField(blank=True, verbose_name='エラーメッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL, verbose_name='実行者')),
                ('csv_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analysis.csvupload', verbose_name='CSVアップロード')),
            ],
            options={
                'verbose_name': '分析結果',
                'verbose_name_plural': '分析結果',
                'ordering': ['-created_at'],
            },
        ),
    ]
