# Generated by Django 5.0.1 on 2025-10-29 03:58

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='カテゴリ名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productcategory', verbose_name='親カテゴリ')),
            ],
            options={
                'verbose_name': '商品カテゴリ',
                'verbose_name_plural': '商品カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='商品名')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='商品コード')),
                ('short_description', models.TextField(max_length=500, verbose_name='短い説明')),
                ('full_description', models.TextField(blank=True, verbose_name='詳細説明')),
                ('target_industries', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='対象業界')),
                ('target_customer_size', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='対象企業規模')),
                ('pain_points_solved', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None, verbose_name='解決する課題')),
                ('key_features', models.JSONField(blank=True, default=list, verbose_name='主要機能')),
                ('pricing_model', models.CharField(blank=True, max_length=100, verbose_name='価格モデル')),
                ('price_range', models.CharField(blank=True, max_length=200, verbose_name='価格帯')),
                ('success_cases', models.JSONField(blank=True, default=list, verbose_name='成功事例')),
                ('competitive_advantages', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None, verbose_name='競合優位性')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('priority', models.IntegerField(default=0, verbose_name='優先度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcategory', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('url', 'URL'), ('pdf', 'PDF'), ('text', 'テキスト入力'), ('manual', '手動入力')], max_length=20, verbose_name='ソースタイプ')),
                ('source_url', models.URLField(blank=True, verbose_name='ソースURL')),
                ('source_file', models.FileField(blank=True, upload_to='products/knowledge/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'docx'])], verbose_name='ソースファイル')),
                ('title', models.CharField(max_length=500, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='コンテンツ')),
                ('structured_data', models.JSONField(blank=True, default=dict, verbose_name='構造化データ')),
                ('embedding_hash', models.CharField(blank=True, max_length=64, verbose_name='埋め込みハッシュ')),
                ('chunk_index', models.IntegerField(default=0, verbose_name='チャンクインデックス')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='処理日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base', to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品ナレッジ',
                'verbose_name_plural': '商品ナレッジ',
                'ordering': ['product', 'chunk_index'],
            },
        ),
    ]
